# production defaults
# see the `dev` profile below for development

app:
  vaadin:
    widgetset: 'app'
    productionMode: "true" # must be string!

server:
  address: 127.0.0.1

vaadin:
  servlet:
    # urlMapping: /app/*
    params:
      productionMode: "${app.vaadin.productionMode}"
      widgetset: "${app.vaadin.widgetset}"
  # see https://github.com/peholmst/vaadin4spring/issues/108#issuecomment-69953039
  static:
    servlet:
      params:
        productionMode: "${app.vaadin.productionMode}"

spring:
  groovy:
    template:
      check-template-location: false

---

spring:
    profiles: dev

app:
  vaadin:
    productionMode: "false" # must be string

